### ISSUE TITLE
Unable to load addon on Firefox 57.0b14 (64-bit) [Beta channel current version]

### ISSUE THREAD

**Issue by mlopatka** [motin/esper-pioneer-shield-study#6]
<img width="819" alt="current_error" src="https://user-images.githubusercontent.com/10152418/32404228-3fb64c1c-c14c-11e7-81d6-ba13eb4d4367.png">

Error received when following specified testplan on Firefox 57.0b14 (64-bit) 
On Mac OS X Sierra 10.12.6

**Comment by motin** [comment]
Blocks https://github.com/motin/esper-pioneer-shield-study/issues/4

**Comment by motin** [comment]
Confirmed / reproduced

**Comment by motin** [comment]
`FIREFOX_BINARY=/Applications/Firefox\ Beta.app/Contents/MacOS/firefox npm run firefox`

```
Starting up firefox
Firefox started
{ WebDriverError: Could not install add-on at '/Users/motin/Dev/Projects/mozilla/shield-studies/based-on-gregs-boilerplate/esper-pioneer-shield-study/dist/linked-addon.xpi': Add-on esper-pioneer-shield-study@shield.mozilla.com is not compatible with application version. add-on minVersion: 56.0. add-on maxVersion: *.
    at Object.throwDecodedError (/Users/motin/Dev/Projects/mozilla/shield-studies/based-on-gregs-boilerplate/esper-pioneer-shield-study/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/Users/motin/Dev/Projects/mozilla/shield-studies/based-on-gregs-boilerplate/esper-pioneer-shield-study/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/Users/motin/Dev/Projects/mozilla/shield-studies/based-on-gregs-boilerplate/esper-pioneer-shield-study/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'WebDriverError',
  remoteStacktrace: 'stack backtrace:\n   0:        0x10307da8e - backtrace::backtrace::trace::h69682bcb53decaf6\n   1:        0x10307dacc - backtrace::capture::Backtrace::new::hdc9d731a957304a6\n   2:        0x102fae434 - webdriver::error::WebDriverError::new::h930061353eac4c81\n   3:        0x102fb801e - geckodriver::marionette::MarionetteSession::response::h451801d534e80d5b\n   4:        0x102f9709b - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::hfda25a6dc0b512aa\n   5:        0x102f6d645 - std::sys_common::backtrace::__rust_begin_short_backtrace::h95009c1d3a320838\n   6:        0x102f7511d - std::panicking::try::do_call::h8c5f07f1fc714fb2\n   7:        0x10312e9cc - __rust_maybe_catch_panic\n   8:        0x102f8af55 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h6a96e09ff4d37bff\n   9:        0x10312ac3b - std::sys::imp::thread::Thread::new::thread_start::h823686b907c11c46\n  10:     0x7fffb5ce293a - _pthread_body\n  11:     0x7fffb5ce2886 - _pthread_start' }
```

**Comment by motin** [comment]
This very clear error message and backtrace means "The add-on is a legacy add-on and since it is unsigned, we won't load it in release or beta builds"

**Comment by motin** [comment]
Bug filed for signing

**Comment by mlopatka** [comment]
Signed xpi successfully loads on Firefox 57.0b14 (64-bit) on Mac OS X Sierra 10.12.6 and delivers payload visible in re:dash. 

closing issue.
